#!/bin/bash

# Add the below lines to your ~/.bashrc-file to autostart
# an ssh-agent with forwarded credentials (ssh/scp,github,etc.)
#
# Change the private-key below if you use a key with another name
# than '~/.ssh/id_rsa'.
#
# If you have multiple keys, just add a separate line for each.

export SSH_AUTH_SOCK=~/.gnupg/S.gpg-agent.ssh

# Start ssh-agent, if not already running.
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
echo "Initialising new SSH agent..."
/usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
echo succeeded
chmod 600 "${SSH_ENV}"
. "${SSH_ENV}" > /dev/null
/usr/bin/ssh-add ~/.ssh/id_rsa;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
. "${SSH_ENV}" > /dev/null
#ps ${SSH_AGENT_PID} doesn't work under cywgin
ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_agent;
}
else
    start_agent;
fi
