#!/bin/bash
# Helper text
opts() { echo "Too few arguments given." 1>&2; echo; }
usage() { echo "Usage: $0 [-s <45|90>] [-p <string>]" 1>&2; echo; exit 1; }
# Getopts loop
while getopts ":s:p:" o; do
    case "${o}" in
        s)
            s=${OPTARG}
            ((s == 45 || s == 90)) || usage
            ;;
        p)
            p=${OPTARG}
            ;;
        *)
            opts
            usage
            ;;
    esac
done
# Shift (subtract) OPTIND to next arg
shift "$((OPTIND-1))"
# IF empty ${s} OR empty ${p}, THEN
if [ -z "${s}" ] || [ -z "${p}" ]; then
    opts
    usage
fi
# IF options are defined, print.
echo "s = ${s}"
echo "p = ${p}"
